export { evaluatePair } from './evaluatePair';
export type { CoreAxis, CoreAxisOutcome, DeclaredDependencyAxis, PairEvaluation, SharedPeerAxis } from './evaluatePair';
export { buildLatestReleasesGrid, latestVersion } from './latestReleasesGrid';
export type { LatestReleasesGrid } from './latestReleasesGrid';
export { verdictSentence, versionLabel } from './verdictSentence';
export { bottleneckSentence, buildVersionSet, installCommand, stackPairSentence } from './versionSet';
export type { Anchors, Bottleneck, NoSet, PartialSet, Pins, PinToRelax, StackPair, VersionSet, VersionSetOptions, VersionSetResult } from './versionSet';
export { candidateVersions } from './versions';
export { buildPairMatrix, PAIR_MATRIX_DEFAULT_LIMIT } from './pairMatrix';
export type { PairMatrix, PairMatrixOptions } from './pairMatrix';
export { VERDICTS } from './verdicts';
export { findTransitiveRangeExample, findVerdictExamples } from './examples';
export type { TransitiveRangeExample, VerdictExamples } from './examples';
